from core.routers.public_routing import classify_public_route
import json
import re

#Faq cases
faq_cases = [
    "¿Que metodos de pago manejan?",
    "¿Que medios de pago aceptan?",
    "¿Aceptan Nequi o Daviplata?",
    "¿Se puede pagar por PSE?",
    "¿Manejan pago contraentrega?",
    "¿Hacen envios a todo Colombia?",
    "¿Tienen cobertura nacional?",
    "¿Hacen envios a mi zona?",
    "¿Mandan pedidos a Pasto?",
    "¿Envian hasta municipios o solo ciudades principales?",
    "¿Cuanto tarda un envio a una ciudad principal?",
    "¿Cuanto demora un envio a una ciudad intermedia?",
    "¿Cuanto se demora un envio a zona rural?",
    "¿Los fines de semana hacen envios?",
    "¿Tambien entregan festivos o solo dias habiles?",
    "¿Por donde puedo comprar?",
    "¿Se puede comprar por WhatsApp?",
    "¿Cuales son los canales de atencion?",
    "¿Los puedo contactar por WhatsApp Business?",
    "¿Tienen correo de soporte?",
    "¿Donde descargo la factura?",
    "¿Como bajo la factura electronica?",
    "¿Como hago seguimiento a un pedido en general?",
    "¿Donde miro el tracking de un pedido?",
    "¿Donde veo el numero de guia?",
    "¿Que significa que un pedido este en preparacion?",
    "¿Que significa el estado 'En camino'?",
    "¿Que significa 'Listo para entrega'?",
    "¿Por que un pedido puede llegar en varios paquetes?",
    "¿Cuantos intentos de entrega hacen normalmente?",
    "¿Como reporto un problema con mi pedido?",
    "¿Donde se reportan productos faltantes o incorrectos?",
    "¿Como hago un reclamo por error de cobro?",
    "Buenas, ¿por que medio los contacto si tengo un problema?",
    "Oe, ¿ustedes si hacen envios a toda Colombia o que?",
    "Parcero, ¿como veo el seguimiento del pedido en general?",
    "¿Donde reviso la factura, pues?",
    "¿Que estados puede tener un pedido?",
    "¿Como funciona el seguimiento del pedido en terminos generales?",
    "¿Cuanto puede tardar en actualizarse el tracking despues del despacho?",
]

# Policy cases
policy_cases = [
    "¿Cual es la politica de devoluciones?",
    "¿Cuanto tiempo tengo para devolver un producto?",
    "¿Cuales son las condiciones para devolver un producto?",
    "¿Que opciones tengo para una devolucion?",
    "¿Puedo pedir cambio por otro producto?",
    "¿Puedo pedir credito en tienda en vez de reembolso?",
    "¿El envio original se reembolsa tambien?",
    "¿Que productos no tienen devolucion?",
    "¿Los productos en promocion tienen cambio o devolucion?",
    "¿Que pasa con un producto marcado como venta final?",
    "¿Aceptan devoluciones de productos usados?",
    "¿Aceptan devolucion si ya no tengo el empaque original?",
    "¿Como es el proceso para solicitar una devolucion?",
    "¿En cuanto tiempo procesan una devolucion?",
    "¿Cuanto tarda el reembolso a tarjeta de credito?",
    "¿Cuanto tarda el reembolso a tarjeta debito?",
    "¿Cuanto tarda el reembolso por PSE?",
    "¿Puedo cancelar una compra antes del despacho?",
    "¿Se puede cancelar despues de que ya va en camino?",
    "¿Puedo cambiar la direccion antes del despacho?",
    "¿Puedo cambiar la direccion si el pedido ya fue despachado?",
    "¿Que cubre la garantia?",
    "¿Que no cubre la garantia?",
    "¿La garantia cubre danos por golpes o caidas?",
    "¿La garantia cubre danos por agua?",
    "¿La garantia cubre desgaste normal?",
    "¿Que pasa si un tecnico no autorizado toca el producto?",
    "¿Cuanto dura la garantia de ropa y calzado?",
    "¿Cuanto dura la garantia de electronica?",
    "¿Como funciona el proceso de garantia?",
    "¿Que resoluciones pueden dar por garantia?",
    "¿Cuanto tarda una reparacion por garantia?",
    "¿Cuanto tarda un reemplazo por garantia?",
    "¿Cuanto tarda un reembolso por garantia?",
    "¿La revision de garantia tiene costo?",
    "¿Necesito factura para reclamar garantia?",
    "¿Donde se solicita la garantia?",
    "¿Si el producto llego incompleto eso entra por garantia?",
    "¿Que pasa si rechazo el paquete al momento de la entrega?",
    "¿Las demoras por clima generan reembolso del envio?",
    "¿Que pasa si la direccion esta mal escrita?",
    "¿Se puede reprogramar la entrega?",
    "¿Puedo redirigir a punto de retiro despues de comprar?",
    "¿Cuando aplica envio gratis?",
    "¿Como calculan el costo de envio en general?",
    "¿Quien responde por el producto mientras esta en transito?",
    "¿Despues de entregado responden por robo o perdida?",
    "¿Cuantos intentos de entrega hacen antes de devolver el paquete?",
    "¿Que pasa si un producto comprado en descuento sale defectuoso?",
    "Parce, si compre algo en promo, ¿igual lo puedo devolver?",
    "Oiga, ¿si el producto ya va en camino todavia lo puedo cancelar o paila?",
    "¿La direccion se puede cambiar despues del despacho o ya no?",
]

inventory_cases = [
    "¿Cuanto cuesta este producto?",
    "¿Que precio tiene este producto?",
    "¿Cual es el valor de este producto?",
    "¿Cuanto vale este articulo?",
    "¿Me regalas el precio de este producto?",
    "¿Cuanto cuesta el iPhone 13?",
    "¿Que precio tiene la air fryer Oster?",
    "¿Cuanto vale este Samsung Galaxy A55?",
    "¿Hay stock de este producto?",
    "¿Tienen stock disponible?",
    "¿Hay existencias de este producto?",
    "¿Tienen existencias?",
    "¿Esta disponible este articulo?",
    "¿Sigue disponible este producto?",
    "¿Todavia lo tienen disponible?",
    "¿Se puede comprar todavia?",
    "¿Este producto aun esta a la venta?",
    "¿Lo tienen en inventario?",
    "¿Esta en existencia?",
    "¿Hay disponibilidad de este producto?",
    "¿Quedan unidades?",
    "¿Cuantas unidades quedan?",
    "¿El producto esta agotado?",
    "¿Hay unidades reservadas o disponibles?",
    "¿Tienen en existencia la licuadora Oster?",
    "¿El producto tiene envio gratis?",
    "¿Este articulo tiene envio gratis?",
    "¿Que productos tienen envio gratis?",
    "¿Este producto esta en promocion?",
    "¿Esta en descuento este producto?",
    "¿Esta en oferta este articulo?",
    "¿Cual es el precio con promocion?",
    "¿Cuanto cuesta con descuento?",
    "¿Cuanto cuesta y si hay stock?",
    "¿Cual es el precio y disponibilidad?",
    "¿Tiene stock y cuanto vale?",
    "¿Hay unidades disponibles y precio?",
    "¿Cuanto cuesta y si esta disponible?",
    "¿Precio y existencia del producto?",
    "Buenas, ¿si tienen este producto o ya se acabo?",
    "Oe, ¿todavia venden este producto o ya no?",
    "Parce, ¿queda stock de esa referencia?",
    "¿Hay de este producto todavia, pues?",
    "¿Cuanto vale esa vaina?",
    "¿A como esta este producto?",
    "¿En cuanto sale este articulo?",
    "¿Si hay unidades de este producto o paila?",
    "¿Me confirmas si este producto tiene promo y stock?",
    "¿Este producto aplica para envio gratis o no?",
    "¿Que precio tiene y si lo puedo comprar ya mismo?",
]

custom_cases = [" holaa, hacen envios a popa? "]

for i, case in enumerate(faq_cases):
    #response handling
    response = classify_public_route(case)
    #Results and metrics for each cycle
    summary = response["response_data"].metrics.get_summary()
    last_usage = summary["agent_invocations"][-1]["usage"]
    print(str(case))
    print(f"Case {i}: {response["route"]}")
   # print(f"Reason: {data["reasoning"]}")
    print(f"Avg cycle (s): {summary['average_cycle_time']}")
    print(f"Per-call usage: {last_usage}")              
    print("-------------------------------------")
